### ISSUE TITLE
What is the reset time of branch_map and pbc in branch prediction mode

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#104]
In the Branch prediction mode:
When the branch_map is full and the correctly predicted branches count **pbc** is less than 31, format 1 is sent. After this, whether both branch_map and pbc need to be cleared to 0 or only branch_map is cleared to 0?

thanks!

**Comment by IainCRobertson** [comment]
Both.  After sending a format 1, the encoder operates in normal branch map mode until 31 correct predictions have been reached.

Iain

From: zhangdujiao ***@***.***>
Sent: 28 April 2024 09:53
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] What is the reset time of branch_map and pbc in branch prediction mode (Issue #104)


In the Branch prediction mode:
When the branch_map is full and the correctly predicted branches count pbc is less than 31, format 1 is sent. After this, whether both branch_map and pbc need to be cleared to 0 or only branch_map is cleared to 0?

thanks!

-

**Comment by zhangdujiao** [comment]
thanks! problem sovled!
