### ISSUE TITLE
How to understand exc_only and er_n in Chapter 9

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#109]
exc_only: Exception or interrupt signalled without simultaneous retirement.
Does this mean that current block only contains exception or interrupt, and no other retired instruction? i.e. itype=1/2 and iretire=0?

er_n: Instruction retirement and exception signalled on the same cycle, or Trace notify trigger.
Does this mean that current block contains exception or interrupt and also other retired instructions? i.e. itype=1/2 and iretire≠0?

thanks!

**Comment by IainCRobertson** [comment]
Yes (to both questions)

Iain

From: zhangdujiao ***@***.***>
Sent: 15 May 2024 08:43
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] How to understand exc_only and er_n in Chapter 9 (Issue #109)


exc_only: Exception or interrupt signalled without simultaneous retirement.
Does this mean that current block only contains exception or interrupt, and no other retired instruction? i.e. itype=1/2 and iretire=0?

er_n: Instruction retirement and exception signalled on the same cycle, or Trace notify trigger.
Does this mean that current block contains exception or interrupt and also other retired instructions? i.e. itype=1/2 and iretire≠0?

thanks!

-

**Comment by IainCRobertson** [comment]
I don't see a problem here.  When a block of instructions retires, you know:

  *   The address of the 1st instruction in the block
  *   The number of half-words in the block (iretires)
  *   The size of the final instruction (lastsize)

From this you can compute the address of the last instruction retired in the block.  Regarding the er_n case vs exc_only, the only difference is whether you use the last address from the previous block (exc_only) or the current block (er_n).

Iain
