### ISSUE TITLE
Are there any recommended value of call_counter_size_p, return_stack_size_p, bpred_size_p and cache_size_p?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#118]
-Implicit return mode
call_counter_size_p
return_stack_size_p

-Branch prediction mode
bpred_size_p

-Jump target cache mode
cache_size_p

**Comment by IainCRobertson** [comment]
This is a trade-off between encoding efficiency and area.  Larger values will always produce more efficient encoding, but cost more in terms of gates.   That said, even relatively small values (e.g. 2) will provide significant efficiency improvements.

Iain

From: zhangdujiao ***@***.***>
Sent: 12 June 2024 04:05
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Are there any recommended value of call_counter_size_p, return_stack_size_p, bpred_size_p and cache_size_p? (Issue #118)


-Implicit return mode
call_counter_size_p
return_stack_size_p

-Branch prediction mode
bpred_size_p

-Jump target cache mode
cache_size_p

-
