### ISSUE TITLE
qual_status value missing of Format 3 subformat 3 in v2.0.3 version

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#121]
qual_status values of 00, 01, 10, 11 are missing in Table 19

**Comment by IainCRobertson** [comment]
Oh - that's a formatting error introduced when converting to AsciiDoc.  @Bill ***@***.***> is something you can fix or do you need me to do it?

Iain

From: zhangdujiao ***@***.***>
Sent: 24 June 2024 09:31
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] qual_status value missing of Format 3 subformat 3 in v2.0.3 version (Issue #121)


qual_status values of 00, 01, 10, 11 are missing in Table 19

-
