### ISSUE TITLE
Should delta address field be added a sign bit at MSB?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#136]
For 64 bits address, if the delta address is "0x0 - 0x4", how to express the result? Should a sign bit be added at MSB to show minus?

**Comment by IainCRobertson** [comment]
That's not necessary and there's nothing special about 64 bits.  0 - 4 = 0xffffffff fffffffc.   If this is reported as the delta, and it is added to the base address (0) the result will be 0xffffffff fffffffc, which is the correct answer.

Iain

From: zhangdujiao ***@***.***>
Sent: 19 August 2024 08:53
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Should delta address field be added a sign bit at MSB? (Issue #136)


For 64 bits address, if the delta address is "0x0 - 0x4", how to express the result? Should a sign bit be added at MSB to show minus?

-
