### ISSUE TITLE
Should TE issue support packet when hart is stalled or enter debug mode?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#137]
TE will receive valid ingress port signal each clock cycle from hart. While if the hart is halted, should TE issue support packet after the last valid ingress port signal?
What is the next inst. should be recognized by TE after the last valid ingress port signal? unqualified? thus TE can report the address of the last valid block...

**Comment by IainCRobertson** [comment]
The TE must ignore all input when halted is high.  It should report the address of the last instruction in the last block retired whilst halted was low, and issue a support packet with qual_status set to indicate trace has ended.  Put another way, every block retired whilst halted is high is treated as unqualified.

Iain

From: zhangdujiao ***@***.***>
Sent: 28 August 2024 08:46
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] Should TE issue support packet when hart is stalled or enter debug mode? (Issue #137)


TE will receive valid ingress port signal each clock cycle from hart. While if the hart is halted, should TE issue support packet after the last valid ingress port signal?
What is the next inst. should be recognized by TE after the last valid ingress port signal? unqualified? thus TE can report the address of the last valid block...

-
