### ISSUE TITLE
TimeStamp width in trBaseEncoder.trTsWidth

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#170]
The width of timestamp is is 0 to 63 bits as defined in trBaseEncoder.trTsWidth. The maximum supported length is 63 bits. 
In the encap protocol, the parameter T represents the number of bytes of TS, and the maximum value is 64 bits.
How to understand this difference, an how to configure 64bits-width TS?

**Comment by IainCRobertson** [comment]
The encapsulation protocol is general and not just for trace.   If the timestamp width selected by trTsWidth is not a multiple of 8 bits, then there will necessarily be some padding bits in the encapsulation.

There is currently no way to specify a 64-bit timestamp for the trace encoder.  If this is a concern, please open an issue against the Trace Control Interface at https://github.com/riscv-non-isa/tg-nexus-trace/issues

Iain

From: Dujiao ***@***.***>
Sent: 11 November 2024 07:46
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] TimeStamp width in trBaseEncoder.trTsWidth (Issue #170)


The width of timestamp is is 0 to 63 bits as defined in trBaseEncoder.trTsWidth. The maximum supported length is 63 bits.
In the encap protocol, the parameter T represents the number of bytes of TS, and the maximum value is 64 bits.
How to understand this difference, an how to configure 64bits-width TS?

-
