### ISSUE TITLE
<Updiscon previous> and <Next inst is exc_only> are satisfied in one block

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-trace-spec#172]
For this situation:
block1 itype = 8 (Uninferable call) ,
block2 itype = 0, iretire >0,
block3 itype = 1, iretire = 0,

Should block2 issue two packets, **te_inst=fmt2 (Updiscon previous)**, and **te_inst = fmt2 (Next inst is exc_only)**.
Or just one packet: **te_inst=fmt2 (Updiscon previous)**, which the updiscon field in fmt2 should be different from notify to indicate the packet is reporting the instruction following an updiscon and is also the instruction before an exception. For this case, the left inst. in block2 will not be traced.

**Comment by IainCRobertson** [comment]
Dujiao,
             It depends on the number of instructions in block 2.  If block 2 contains more than 1 instruction then it will generate 2 packets (one containing the 1st instruction in the block, and one containing the address of the last).  But if block2 is just a single instruction then it only needs to generate a single packet.

Iain

From: Dujiao ***@***.***>
Sent: 15 November 2024 09:23
To: riscv-non-isa/riscv-trace-spec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [riscv-non-isa/riscv-trace-spec] <Updiscon previous> and <Next inst is exc_only> are satisfied in one block (Issue #172)


For this situation:
block1 itype = 8 (Uninferable call) ,
block2 itype = 0, iretire >0,
block3 itype = 1, iretire = 0,

Should block2 issue two packets, te_inst=fmt2 (Updiscon previous), and te_inst = fmt2 (Next inst is exc_only).
Or just one packet: te_inst=fmt2 (Updiscon previous), witch the updiscon field in fmt2 should be different from notify to indicate the packet is reporting the instruction following an updiscon and is also the instruction before an exception.

-

**Comment by zhangdujiao** [comment]
thx Iain :)
