### ISSUE TITLE
Spelling of inferable/inferrable

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv-non-isa/riscv-trace-spec#21]
I searched the document for "inferrable" and had 25 matches (both "inferrable" and as a substring of "uninferrable").  Searching for "inferable" gives 33 matches (also for both terms).

For instance, table 3.1 has different spellings back-to-back:
```
8: Uninferable call;
9: Inferrable call;
```

It appears that both spellings may be correct but I suggest that just one be used for consistency and for searchability.

**Comment by allenjbaum** [comment]
I noticed that also.
A web search seems to indicate that both can have either one or 2 "R"s; I didn't see a preference for one or the other. In the spec, I think the two words are consistent within themselves, at least.
