### ISSUE TITLE
What trigger type will fire trace action?

### ISSUE THREAD

**Issue by larryrong** [riscv-non-isa/riscv-trace-spec#78]
Hello, 

I have a question about `Using trigger outputs from the Debug Module`. The latest debug specification adds a new trigger type (`mcontrol6`) to support future features and `mcontrol` will be considered obsolete. Thus, I just want to confirm that _`mcontrol6` supports actions 2-4_ ?

Thanks,
Larry

**Comment by pdonahue-ventana** [comment]
All triggers are able to support all actions.  The description of the action field of mcontrol6 says:
> The action to take when the trigger fires. The values are explained in Table 5.1.

Table 5.1 is the same table used by mcontrol, icount, itrigger, etrigger, and tmexttrigger.

Like with anything else, an implementation may choose to only support a subset of actions on any particular trigger.  You'd have to confirm with the particular implementation whether it supports actions 2-4 on its mcontrol6 trigger(s).
